### ISSUE TITLE
add layout

### ISSUE THREAD

**Issue by durandom** [operate-first/operate-first.github.io#1]
we should add a layout component like described at https://www.gatsbyjs.com/docs/recipes/pages-layouts/ and here https://github.com/gatsbyjs/gatsby-starter-blog/blob/master/src/components/layout.js

**Comment by bryanmontalvan** [comment]
@durandom I'm a bit confused on what exactly you want me to follow?

The page-layout on the docs shows 
```
|-- /.cache
|-- /plugins
|-- /public
|-- /src
    |-- /pages
    |-- /templates
    |-- html.js
|-- /static
|-- gatsby-config.js
|-- gatsby-node.js
|-- gatsby-ssr.js
|-- gatsby-browser.js
```

Our current is:
```
|-- /.cache
|-- /plugins
|-- /public
|-- /src
    |-- /components
        |-- /homepage
            |-- About.js
            |-- Contact.js
            |-- Faq.js
            |-- HomePage.js
            |-- Interest.js
            |-- Navbar.js
    |-- /images
    |-- /pages
|-- .aicoe-ci.yaml
|-- .gitignore
|-- .pre-commit-config.yaml
|-- .prettierignore
|-- .prow.yaml
|-- gatsby-config.js
|-- OWNERS
|-- package-lock.json
|-- package.json
```

So what's really different is that the core JS file which is inside `/pages` so I'm assuming you would like `src/pages/index.js` to move to `/src/index.js`. As for the rest I'm confused exactly what you would like. Since `/templates` from the docs is different from `/components`

**Comment by durandom** [comment]
Just keep our current structure, introduce a `Layout.js` component and use it in `index.js`, so that we can use the same in  e.g `about.js`
