### ISSUE TITLE
go live

### ISSUE THREAD

**Issue by durandom** [operate-first/operate-first.github.io#29]
Let's talk about how to make the transition

- [ ] rename https://github.com/operate-first/operate-first.github.io to operate-first.github.io-old
- [ ] rename https://github.com/operate-first/website-ng to operate-first.cloud
- [ ] configure operate-first.github.io-old to be available at operate-first.cloud/old
- [ ] configure operate-first.cloud be available at operate-first.cloud

@HumairAK can we do steps 1 and 2 manually and then update https://github.com/operate-first/common or should we initiate the transition via a PR to common?

**Comment by HumairAK** [comment]
@durandom as far as I understand, you need to do this in 2 prs, first is to rename the repo to `old`, then to rename the new repo. 
Previously we had to rename the `sre` repo to `operations`, so that a new `sre` repo could be created, to do this we did the following: 

rename: https://github.com/operate-first/common/commit/164d1942319465a0ec8c01668dce8a9bf2f837b6
add new: https://github.com/operate-first/common/commit/188ed5ba8a6f625373cce7180b64bf8fb8d30bdf

notice the addition of the `previously` field during rename, and its removal when the new repo is created. 
for this situation, you would add the `previously` to the old, and rename it thus. Then once renamed, you would create a new PR removing the `previously`, and rename the `website-ng` to `operate-first.cloud` and add the `preiouvlys: [website-ng]` to it's spec. Hope that makes sense. 

Couldn't find [docs on this but here's the peribolos pr for it](https://github.com/kubernetes/test-infra/pull/14934).

**Comment by durandom** [comment]
it's done
